name: calculator_flutter
description: Devskiller Flutter Calculator


version: 1.0.0+1

environment:
  sdk: ">=2.14.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.3

dev_dependencies:
  test: ^1.16.8
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
